### ISSUE TITLE
Check compatibility with Cardano Node 8.0.0

### ISSUE THREAD

**Issue by satran004** [bloxbean/yaci#10]
Known issues:

1. Protocol param local state query fails with following error

```
WARN  [2023-05-11 13:43:44,212] io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
! java.lang.NullPointerException: Cannot invoke "java.math.BigInteger.intValue()" because the return value of "com.bloxbean.cardano.yaci.core.util.CborSerializationUtil.toBigInteger(co.nstant.in.cbor.model.DataItem)" is null
! at com.bloxbean.cardano.yaci.core.util.CborSerializationUtil.toInt(CborSerializationUtil.java:55)
! at com.bloxbean.cardano.yaci.core.protocol.localstate.queries.CurrentProtocolParamsQuery.deserializeResult(CurrentProtocolParamsQuery.java:103)

```

2. Era query like UtxoByAddress doesn't work

**Comment by satran004** [comment]
- With 8.0, GenesisBlockFinder doesn't return the correct start point, so sync fails.
